import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Calendar, Globe, Sparkles } from 'lucide-react';
import { format } from 'date-fns';
import { IReport } from '../api/reportApi';

interface ReportHeaderProps {
  report: IReport;
}

export function ReportHeader({ report }: ReportHeaderProps) {
  return (
    <Card className="border-indigo-500/20 bg-gradient-to-br from-indigo-500/10 via-purple-500/5 to-transparent p-6">
      <div className="flex flex-col items-start justify-between gap-4 md:flex-row md:items-center">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-bold tracking-tight">
              Optimization Report
            </h1>
            <Badge
              variant={report.status === 'Completed' ? 'default' : 'secondary'}
              className="bg-indigo-500 hover:bg-indigo-600"
            >
              {report.status}
            </Badge>
          </div>
          <div className="flex flex-wrap items-center gap-4 text-sm text-muted-foreground">
            <a
              href={report.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 transition-colors hover:text-indigo-400"
            >
              <Globe className="h-4 w-4" />
              {report.url}
            </a>
            <div className="flex items-center gap-1.5">
              <Calendar className="h-4 w-4" />
              {format(new Date(report.createdAt), 'MMM d, yyyy')}
            </div>
            <div className="flex items-center gap-1.5">
              <Sparkles className="h-4 w-4" />
              {report.experiments.length} Experiments generated by{' '}
              {report.aiModel}
            </div>
          </div>
        </div>

        {report.screenshotUrl && (
          <div className="hidden h-20 w-full shrink-0 overflow-hidden rounded-md border border-border bg-muted md:block md:w-32">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={report.screenshotUrl}
              alt="Page Preview"
              className="h-full w-full object-cover object-top opacity-80 transition-opacity hover:opacity-100"
            />
          </div>
        )}
      </div>
    </Card>
  );
}
